### ISSUE TITLE
migrate to null safety

### ISSUE THREAD

**Issue by deadsoul44** [Flutterando/flutter_mobx_helpers#2]
migrate to null safety

**Comment by denisviana** [comment]
I just opened a PR. As long as it's not approved, you can use it from here.
```
flutter_mobx_helpers:
    git:
      url: https://github.com/denisviana/flutter_mobx_helpers.git
      ref: master
```
